export const models = {
   users: {
      lid: null,
      afk: -1,
      afkReason: '',
      afkObj: {},
      banned: false,
      ban_temporary: 0,
      ban_times: 0,
      premium: false,
      expired: 0,
      lastseen: 0,
      hit: 0,
      warning: 0,
      example: []
   },
   groups: {
      activity: 0,
      antidelete: false,
      antilink: false,
      antivirtex: false,
      antitagsw: false,
      filter: false,
      left: false,
      localonly: false,
      mute: false,
      viewonce: false,
      autosticker: false,
      member: {},
      text_left: '',
      text_welcome: '',
      welcome: true,
      expired: 0,
      stay: false
   },
   chats: {
      chat: 0,
      lastchat: 0,
      lastseen: 0
   },
   setting: {
      autobackup: false,
      autodownload: true,
      antispam: false,
      debug: false,
      notifier: false,
      error: [],
      hidden: [],
      pluginDisable: [],
      receiver: [],
      groupmode: false,
      sk_pack: '',
      sk_author: 'ᴇᴍᴘɪʀᴇ ʙᴏᴛ',
      self: false,
      noprefix: false,
      multiprefix: true,
      prefix: ['.', '#', '!', '/'],
      toxic: ["puta", "verga", "mamaverga", "pelaverga", "hijueputa", "mmverga", "chucha", "chuchatumadre", "hijodeperra", "hijadeperra", "hijodeputa", "mmguevo", "puto", "pelaguevo", "maricon", "mmhuevo", "mamahuevo", "mamaguevo", "mmverg", "mmver", "hijoputa", "hijueputa", "hijaputa", "tonto", "tonta", "conchadetumadre", "caraculo", "careverga", "caradeverga", "carevg", "caradevg", "caravg", "careculo", "caradeculo", "bobo", "boba", "pendejo", "pendeja",  "bruto", "bruta"],
      online: true,
      onlyprefix: '+',
      owners: ['593985807958'],
      lastReset: new Date * 1,
      msg: 'Hola +tag 🪸\nSoy un sistema automatizado (WhatsApp Bot) que puede ayudar a hacer algo, buscar y obtener datos / información solo por WhatsApp.\n\n◦ *Module* : +module\n◦ *Database* : +db\n◦ *Library* : Baileys +version\n◦ *Rest API* : https://api.crysis.my.id\n◦ *Source* : https://github.com/crysis/empire-bot\n\nSi encuentra un error o desea actualizar el plan premium, comuníquese con el Administrador.',
      style: 5,
      cover: 'https://telegra.ph/file/6fba2e7bba8b9d81fd6f0.jpg',
      link: 'https://chat.whatsapp.com/JNJJyqivsfk4ClQ6FCSZcj?mode=wwc'
   }
}
